### ISSUE TITLE
Installation on Windows Server

### ISSUE THREAD

**Issue by Semyazz** [epitron/redmine_ultraviolet#12]
is there any way to install this plugin on Windows 2008 R2 server. In my company we are using M$ software and i had to deploy Redmine on Windows, but i'd really like to use Ultraviolet. How can i do that?

**Comment by epitron** [comment]
Hmm... no idea. Maybe jRuby? I think someone managed to get it working on jRuby.

Anyone got any ideas?

**Comment by cmartininfosol** [comment]
I got it installed on Windows Server 2003.  The rails script didn't work for me.  I had to download the git and place it into the plugins folder myself.  Oh and i'm still pre ruby 1.9 so i did "gem install oniguruma" to get that installed first.  Hope that helped some.

Now for me, time to figure out how to get the syntax highlighting to work.  I noted my old &lt;pre&gt;&lt;code class="xml"&gt;&lt;/code&gt;&lt;/pre&gt; blocks didnt convert

**Comment by epitron** [comment]
Good to know that oniguruma works on Windows!

**Comment by archonwang** [comment]
If so .I do think it should update the installation guide in Readme.rdoc.

**Comment by epitron** [comment]
Updated!

**Comment by epitron** [comment]
(Are those instructions correct?)

**Comment by cmartininfosol** [comment]
Yeah for windows i think it was just a "gem install" command needed
