### ISSUE TITLE
Unable to get syntax highlighting to show up

### ISSUE THREAD

**Issue by cmartininfosol** [epitron/redmine_ultraviolet#13]
Hello,

Looking forward to using your redmine plugin, but I think i'm missing a key bit of knowledge to get this going.  I've installed oniguruma and ultraviolet gems.  I've downloaded the code folder and placed it in the vendor/plugins folder.  Restarted the service, and things are up and going.  I noted the new field in my profile to choose the default theme for highlighting.

Now the thing is, when i open a ticket that has used code syntax highlighting in the past, the highlighting is not applied.  It's still using the default coderay highlighting.  In the body of the redmine ticket the xml code is wrapped with these tags

&lt;pre&gt;&lt;code class="xml"&gt;&lt;/code&gt;&lt;pre&gt;

I've even tried to create a new ticket and preview the posting.  The highlighting is still using the old coderay.

Thanks in advance for your time

**Comment by cmartininfosol** [comment]
If this helps, i'm on Redmine 1.2.0

**Comment by epitron** [comment]
Oh, this plugin only deals with highlighting files in the repo.

There is a fork of this plugin by Erik which applies ultraviolet to the wiki -- maybe that works on the tickets too?

Check it: https://github.com/erikkallen/redmine_ultraviolet

**Comment by cmartininfosol** [comment]
Ahh, then yep.  It's working just fine for files in the repo.  Thanks for the reply.  I'll take a look at the other fork :)

**Comment by cmartininfosol** [comment]
Well, that doesn't seem to behave.  Even started to setup a wiki to see if it only worked there. Now code syntax highlighting in both the wiki and in issue tickets dont work.  Not sure why, not familiar with ruby.  Thanks again tho for pointing me in the right direction.

**Comment by epitron** [comment]
The fork doesn't even do the wiki? Maybe you should file a bug with Erik? :)

**Comment by cmartininfosol** [comment]
I wanted to, but the Issues tab is not on his fork.  Possibly disabled?  I'm not too sure, not terribly familiar with the site.

**Comment by neilfws** [comment]
Erik's fork does not include the fix in  app /views/common/_file.rhtml required for Redmine 1.3. Once this edit is made, UV highlighting works in repository view but not wiki view. It's unfortunate that Erik's fork has little documentation or ways to contact him for more details.

**Comment by epitron** [comment]
Indeed...

Perhaps I should make erik's fork a branch of my repo, and apply the 1.3 fix.

**Comment by neilfws** [comment]
In fact I was mistaken on all counts! UV does work on wiki view in Erik's fork and he replied promptly to questions over at his fork. Only remaining issue is the 1.3 fix.

**Comment by epitron** [comment]
Woot!
