### ISSUE TITLE
rake aborted no such file to load -- uv

### ISSUE THREAD

**Issue by urmel1960** [epitron/redmine_ultraviolet#16]
Hi,

tried to install your plugin according to your nstructions. Then "rake db:migrate_plugins RAILS_ENV=production" leads into the error message above.

Any suggestion/advice is highly welcome.

Thanks

**Comment by epitron** [comment]
Do you have the "uv" gem installed? :)

**Comment by urmel1960** [comment]
I did "gem install ultraviolet". I am afraid that this is not uv ?? :-)

I now  tried to install uv :

/usr/lib/ruby_enterprise/bin> ./gem install uv
Fetching: spox-plist-3.0.1.gem (100%)
ERROR:  Error installing uv:
        spox-plist requires Ruby version >= 1.9.0.

**Comment by akuznecov** [comment]
same problem with 

> cannot load such file -- uv

uv gem already installed:

> $ gem install uv
> Fetching: spox-plist-3.0.1.gem (100%)
> Fetching: spox-textpow-0.10.3.gem (100%)
> Fetching: uv-0.0.7.5.gem (100%)
> Successfully installed spox-plist-3.0.1
> Successfully installed spox-textpow-0.10.3
> Successfully installed uv-0.0.7.5
> 3 gems installed
> Installing ri documentation for spox-plist-3.0.1...
> Installing ri documentation for spox-textpow-0.10.3...
> Installing ri documentation for uv-0.0.7.5...
> Installing RDoc documentation for spox-plist-3.0.1...
> Installing RDoc documentation for spox-textpow-0.10.3...
> Installing RDoc documentation for uv-0.0.7.5...

Redmine 1.4.1 / Rube 1.9.3-p194

**Comment by cmartininfosol** [comment]
I too am having this same issue.  I do have uv installed as well

C:\RM>gem list uv

**\* LOCAL GEMS ***

uv (0.0.7.5)

**Comment by JanSimek** [comment]
Same as above. Using Redmine 2.1.3 with Rails 3.2.6.

**Comment by Utopism** [comment]
Hi, You just have to load the uv gem in the Gemfile.
Add the following line :
gem "uv"

**Comment by sdfg2** [comment]
uv is ultraviolet for Ruby 1.9 onward.

So yes, 'gem install uv', then I added a Gemfile into the plugin directory 'gem "uv"'.  Do 'bundle install', then migration then works properly.
