### ISSUE TITLE
Does this syntax highlight plugin only work on repository view, not on Wiki page and issue comment?

### ISSUE THREAD

**Issue by shuozhifenxi** [epitron/redmine_ultraviolet#17]
Hi

First of all, thank you very much for providing this great plugin.

The syntax highlight works fine when I review repository code of my project, but it does not work for the code pieces in wiki pages and issue comments.

Is it the limitation of the plugin or I missed some configuration?

**Comment by lgwapnitsky** [comment]
I'm not even seeing it in my repository view.  Assistance on getting this to work?

Thanks

**Comment by epitron** [comment]
Sorry for the lateness of my reply!

Unfortunately, this plugin only deals with highlighting files in the repo.

There is a fork of this plugin by Erik which applies ultraviolet to the wiki.

Check it: https://github.com/erikkallen/redmine_ultraviolet
