### ISSUE TITLE
Perl

### ISSUE THREAD

**Issue by klopp** [epitron/redmine_ultraviolet#24]
Perl syntax does not work?

![redmine](https://cloud.githubusercontent.com/assets/3979145/9125512/5b75f138-3caa-11e5-9cd2-77c766606e57.jpg)

**Comment by epitron** [comment]
Oh, this plugin only deals with highlighting files in the repo.

There is a fork of this plugin by Erik which applies ultraviolet to the wiki.

Check it: https://github.com/erikkallen/redmine_ultraviolet

**Comment by hegemogy** [comment]
I had difficulty getting either of these to work, but successfully loaded a later fork https://github.com/jbbarth/redmine_ultraviolet into Redmine 3.2.0:
- gem install ultraviolet
- gem install uv
- cd /var/www/redmine/plugins
- git clone git://github.com/jbbarth/redmine_ultraviolet.git
- bundle exec rake redmine:plugins NAME=redmine_ultraviolet RAILS_ENV=production
- touch ../tmp/restart.txt

**NOTE:** I had to edit /var/www/redmine/plugins/redmine_ultraviolet/lib/uv_extension.rb to skip `name == "cucumber_steps"` as that syntax file was failing with a fatal error.

> Environment:
>   Redmine version                3.2.0.stable.15148
>   Ruby version                   2.0.0-p598 (2014-11-13) [x86_64-linux]
>   Rails version                  4.2.5.1
>   Environment                    production
>   Database adapter               Mysql2
> SCM:
>   Subversion                     1.7.14
>   Git                            1.8.3.1
>   Filesystem  
> Redmine plugins:
>   redmine_agile                  1.4.0
>   redmine_ultraviolet            0.0.3
