### ISSUE TITLE
I can't see "Add review" and "Review assignments" link menu by code review plugin.

### ISSUE THREAD

**Issue by xyz37** [epitron/redmine_ultraviolet#3]
Thanks a lot of your effort.
and I forked Oniguruma, Ultraviolet gem installed on Windows 2008 R2
but I success your plugin.

Then I install Code Review plugin 
but I couldn't see "Add review" and "Review assignments" link menu in repository.

oniguruma 1.1.0
ultraviolet 0.10.2
and other environments are

---

About your application's environment
Ruby version              1.8.7 (i386-mingw32)
RubyGems version          1.3.6
Rack version              1.0
Rails version             2.3.5
Active Record version     2.3.5
Active Resource version   2.3.5
Action Mailer version     2.3.5
Active Support version    2.3.5
Application root          D:/CI/Redmine
Environment               production
Database adapter          mysql
Database schema version   20100221100219

About your Redmine plugins
Charts Plugin                                    0.0.14
Redmine Wiki Issue Details plugin                0.1.0
Bulk Time Entry                                  0.5.0
Redmine Question plugin                          0.3.0
Redmine Code Review plugin                       0.3.0
Advanced report plugin                           0.0.3
ezFAQ plugin                                     0.3.5
Redmine Ultraviolet Syntax highlighting plugin   0.0.1
Thumbnails plugin                                0.1.1
Redmine Bugcloud plugin                          0.0.2.1
Advanced roadmap plugin                          0.0.6
Issues XLS export                                0.0.3
Tab Plugin                                       0.3.1
Screenshot Paste                                 1.0.2
Redmine Schedules plugin                         0.4.2
Libsvn                                           0.0.1
Redmine Graphs plugin                            0.1.0
Timesheet Plugin                                 0.6.0
Redmine Checkout plugin                          0.3
Scrumdashboard plugin                            1.2

---

**\* LOCAL GEMS ***

actionmailer (2.3.5)
actionpack (2.3.5)
activerecord (2.3.5)
activeresource (2.3.5)
activesupport (2.3.5)
cgi_multipart_eof_fix (2.5.0)
config (0.0.1)
gchart (1.0.0)
gem_plugin (0.2.3)
git (1.2.5)
holidays (0.9.3)
mini_magick (1.2.5)
mongrel (1.1.5)
mongrel_service (0.3.4)
mysql (2.8.1)
oniguruma (1.1.0)
plist (3.1.0)
rack (1.0.1)
rails (2.3.5)
rake (0.8.7)
rmagick (2.12.0)
ruby-ole (1.2.10)
ruby-openid (2.1.7)
rubygems-update (1.3.6)
rubytree (0.6.2)
spreadsheet (0.6.4.1)
textpow (0.10.1)
ultraviolet (0.10.2)
win32-service (0.5.2)

---

Please fixed this bug... :-)

I was started webrick server below warning occured.
What's happening?
It's not that I do ruby 1.9.1?

---

./script/../config/../vendor/rails/railties/lib/rails/gem_dependency.rb:119:Warn
ing: Gem::Dependency#version_requirements is deprecated and will be removed on o
r after August 2010.  Use #requirement

**Comment by epitron** [comment]
Hi,

I don't think I can help you since I don't use the Code Review plugin.

You could try to start solving the problem by comparing the plugin's views with the Code Review plugin's views. Maybe Code Review is injecting some new stuff into the views, and my plugin is overriding that.
