### ISSUE TITLE
plugin installed but not used

### ISSUE THREAD

**Issue by k2s** [epitron/redmine_ultraviolet#6]
method syntax_highlight_with_uv_syntax_highlight is never calles

Redmine 1.1.0.devel (MySQL)

pls. advice

**Comment by epitron** [comment]
Hmmm... I don't actually have a redmine install at the moment. But I think it was written for Redmine 0.7, so some part of the Redmine plugin API could've definitely changed.

**Comment by epitron** [comment]
redmine_ultraviolet works fine for me in 1.1.3 with no modifications. Tell me if that helps!
