### ISSUE TITLE
Redmine 1.1.x support

### ISSUE THREAD

**Issue by wyuenho** [epitron/redmine_ultraviolet#9]
This awesome plugin doesn't seem to work on Redmine 1.1.x. Ultraviolet is a much much better syntax highlighter than Coderay, it'd be nice if this plugin worked on 1.1.x.

**Comment by epitron** [comment]
Agreed. :D

I'm still using an older version of Redmine, unfortunately. Would you be interested in helping port it to the new version? The plugin is insanely simple -- it's like 100 lines of code. :)

**Comment by wyuenho** [comment]
Oy. That means I have to learn Ruby :P. I don't know, I might look into it when I have time. This might be a nice little exercise.

**Comment by joeglenn** [comment]
I'd love to see an update to work with 1.1.x !

**Comment by epitron** [comment]
Me too!

**Comment by saucissons** [comment]
Am I the only one with this lovely plugin working on redmine 1.1.3 ???

**Comment by epitron** [comment]
Hah! Funny you should mention it... I just installed 1.1.3 a few minutes ago, and redmine_ultraviolet works fine!

What problem were you guys having? Could you give me some more info?

**Comment by wyuenho** [comment]
My Redmine instance is connected to 2 Mercurial repositories hosting 2 python projects. Ever since I installed redmine_ultraviolet, all the source files lost syntax highlighting. It's just black on white for every file. It doesn't work.

**Comment by epitron** [comment]
Oh, I see. It sounds like Ultraviolet is working, but it has no syntax files. Either that, or mercurial is confusing the plugin's filetype detector (which just looks at file extensions).

If you want to add some debug information, go here:
https://github.com/epitron/redmine_ultraviolet/blob/master/lib/ultraviolet_syntax_patch.rb#L84

Then change that line to something like:

```
return Uv.parse(content, "xhtml", syntax_name, true, @uv_theme_name) + "<pre>filename: #{name.inspect}, syntax: #{syntax_name}, user theme: #{@uv_theme_name}</pre>"
```

You could also test ultraviolet itself and see if its tests or example scripts work.

**Comment by wyuenho** [comment]
I have this for .py files:

syntax: python, user theme: eiffel

**Comment by epitron** [comment]
I've never tried that theme. Maybe it's broken? Try changing it.

If that doesn't work, see if Ultraviolet works by itself.

**Comment by wyuenho** [comment]
It was started with the default theme first and then I tried a couple different ones. They all give the same result.

**Comment by epitron** [comment]
Well, it doesn't appear to be a problem with my plugin -- Ultraviolet is just returning unhighlighted stuff! I'd look there.

**Comment by jerryorta** [comment]
I may have a little more information that may help troubleshoot. I hope. I'm unsuccessful getting this plugin to run thus far, and this is what I have.

I'm running redmine 1.1.3 as well. My issue is that I get an error that uv can not be found (at least that is what the log tells me). Ultraviolet and it's dependencies installed fine, and tests fine.

Here are my specs:
CentOS 5
Linux 2.6.18-028stab070.14

Error log:
Error message:
no such file to load -- uv (MissingSourceFile)
Exception class:
PhusionPassenger::UnknownError
Application root:
/var/www/vhosts/<domainname>.com/projects.<domainname>.com
Backtrace:

# File    Line    Location

0   /var/www/vhosts/<domainname>.com/projects.<domainname>.com/vendor/rails/activesupport/lib/active_support/dependencies.rb    158 in `require'
1   /var/www/vhosts/<domainname>.com/projects.<domainname>.com/vendor/rails/activesupport/lib/active_support/dependencies.rb    158 in`require'
2   /var/www/vhosts/<domainname>.com/projects.<domainname>.com/vendor/plugins/redmine_ultraviolet/init.rb   3   in `evaluate_init_rb'
3   /var/www/vhosts/<domainname>.com/projects.<domainname>.com/vendor/rails/railties/lib/rails/plugin.rb    158 in`evaluate_init_rb'
4   /var/www/vhosts/<domainname>.com/projects.<domainname>.com/vendor/rails/activesupport/lib/active_support/core_ext/kernel/reporting.rb   11  in `silence_warnings'
5   /var/www/vhosts/<domainname>.com/projects.<domainname>.com/vendor/rails/railties/lib/rails/plugin.rb    154 in`evaluate_init_rb'
6   /var/www/vhosts/<domainname>.com/projects.<domainname>.com/vendor/rails/railties/lib/rails/plugin.rb    48  in `load'
7   /var/www/vhosts/<domainname>.com/projects.<domainname>.com/config/../vendor/plugins/engines/lib/engines/plugin.rb   44  in`load'
8   /var/www/vhosts/<domainname>.com/projects.<domainname>.com/vendor/rails/railties/lib/rails/plugin/loader.rb 38  in `load_plugins'
9   /var/www/vhosts/<domainname>.com/projects.<domainname>.com/vendor/rails/railties/lib/rails/plugin/loader.rb 37  in`each'
10  /var/www/vhosts/<domainname>.com/projects.<domainname>.com/vendor/rails/railties/lib/rails/plugin/loader.rb 37  in `load_plugins'
11  /var/www/vhosts/<domainname>.com/projects.<domainname>.com/vendor/rails/railties/lib/initializer.rb 369 in`load_plugins'
12  /var/www/vhosts/<domainname>.com/projects.<domainname>.com/vendor/rails/railties/lib/initializer.rb 165 in `process'
13  /var/www/vhosts/<domainname>.com/projects.<domainname>.com/vendor/rails/railties/lib/initializer.rb 113 in`send'
14  /var/www/vhosts/<domainname>.com/projects.<domainname>.com/vendor/rails/railties/lib/initializer.rb 113 in `run'
15  /var/www/vhosts/<domainname>.com/projects.<domainname>.com/config/environment.rb    20  
16  /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/classic_rails/application_spawner.rb    222 in`require'
17  /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/classic_rails/application_spawner.rb    222 in `preload_application'
18  /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/classic_rails/application_spawner.rb    181 in`initialize_server'
19  /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/utils.rb    572 in `report_app_init_status'
20  /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/classic_rails/application_spawner.rb    174 in`initialize_server'
21  /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb  204 in `start_synchronously'
22  /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb  180 in`start'
23  /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/classic_rails/application_spawner.rb    149 in `start'
24  /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/spawn_manager.rb    219 in`spawn_rails_application'
25  /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server_collection.rb   132 in `lookup_or_add'
26  /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/spawn_manager.rb    214 in`spawn_rails_application'
27  /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server_collection.rb   82  in `synchronize'
28  /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server_collection.rb   79  in`synchronize'
29  /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/spawn_manager.rb    213 in `spawn_rails_application'
30  /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/spawn_manager.rb    132 in`spawn_application'
31  /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/spawn_manager.rb    275 in `handle_spawn_application'
32  /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb  357 in`**send**'
33  /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb  357 in `server_main_loop'
34  /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/lib/phusion_passenger/abstract_server.rb  206 in`start_synchronously'
35  /usr/local/lib/ruby/gems/1.8/gems/passenger-3.0.7/helper-scripts/passenger-spawn-server 99

**Comment by epitron** [comment]
For whatever reason, the 'uv' gem isn't being picked up by your installation. You're going to have to figure this one out yourself -- there are too many possible ways this could go wrong. :)

**Comment by epitron** [comment]
Going once... going twice... closed!
